name: Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      run: |
        sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer
        echo 'export PATH="/usr/bin:$PATH"' >> $GITHUB_PATH
    - name: Build and Test
      run: |
        swift build
        swift test --enable-code-coverage
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: .build/debug/codecov/*.json
        fail_ci_if_error: true

