name: Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        echo 'export PATH="/usr/bin:$PATH"' >> $GITHUB_PATH
    - name: Build and Test
      run: |
        xcodebuild clean build test -project "SundeedQLiteLibrary.xcodeproj" -scheme "SundeedQLiteLibrary" -destination "platform=iOS Simulator,OS=16.2,name=iPhone 13 Pro" -enableCodeCoverage YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -derivedDataPath derivedData/  CONFIGURATION_BUILD_DIR=build/
    - name: Install Slather
      run: gem install slather
    - name: Convert .xcresult to .lcov
      run: slather coverage --binary-basename SundeedQLiteLibrary --input-format profdata --scheme SundeedQLiteLibrary --build-directory derivedData/Build/Products --output-directory . --simple-output --ignore "../**/*/Xcode*" --ignore "../*/Xcode.app/Contents/Developer/**/*" --ignore "../**/*/usr/include/**/*" --ignore "Pods/**/*" SundeedQLiteLibrary.xcodeproj
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cobertura.xml
        fail_ci_if_error: true

