name: Test

on:
  push:
    branches:
      - '**'
env:
  DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        echo 'export PATH="/usr/bin:$PATH"' >> $GITHUB_PATH
    - name: Build and Test
      run: |
        xcodebuild clean build test -project "SundeedQLiteLibrary.xcodeproj" -scheme "SundeedQLiteLibrary" -destination "platform=iOS Simulator,OS=26.0,name=iPhone 17 Pro" -enableCodeCoverage YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
    - name: Install Slather
      run: gem install slather
    - name: Convert .xcresult to .lcov
      run: slather coverage --cobertura-xml --input-format profdata --scheme SundeedQLiteLibrary --output-directory . --ignore "Pods/**/*" SundeedQLiteLibrary.xcodeproj
    - name: List files
      run: ls -ltr
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cobertura.xml
        fail_ci_if_error: true

